// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jAG8PEYF0yC_ldbQ7DV8IwTsYNaB1Hg',
    appId: '1:441755848134:android:e90cd62b56ffe4fbf0b6c7',
    messagingSenderId: '441755848134',
    projectId: 'steps-tracker-6ef45',
    storageBucket: 'steps-tracker-6ef45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibSuQt5-USyeB1SbU7PqP9yrdpteztvQ',
    appId: '1:441755848134:ios:d68bccac0348f068f0b6c7',
    messagingSenderId: '441755848134',
    projectId: 'steps-tracker-6ef45',
    storageBucket: 'steps-tracker-6ef45.appspot.com',
    iosClientId: '441755848134-l7o4136q39n2d1gcj2bti2qtoa9l4gth.apps.googleusercontent.com',
    iosBundleId: 'com.mustafahasria.stepstracker.pedometer',
  );
}
